version: '3'
services:
  db:
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
  sycamore:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/whimsy

