// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/gorilla/mux"
	"gorm.io/gorm"
)

// Injectors from inject.go:

func buildRouter(ctx context.Context) (*mux.Router, func(), error) {
	db, cleanup, err := setupDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := setupGorm(ctx, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	privateKey, err := setupPrivateKey()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cmdPublicKeyStr, err := setupPublicKey(privateKey)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	router := setupRouter(ctx, gormDB, cmdPublicKeyStr)
	return router, func() {
		cleanup()
	}, nil
}

func buildGorm(ctx context.Context) (*gorm.DB, func(), error) {
	db, cleanup, err := setupDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := setupGorm(ctx, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return gormDB, func() {
		cleanup()
	}, nil
}
